checks:
    php: true
build:
    environment:
        php:
            version: 7.0.8
    tests:
        override:
          -
            command: 'bin/phpspec run -f progress -c phpspec-ci.yml'
            coverage:
              file: 'coverage.clover'
              format: 'php-clover'